language: go

go:
  - 1.x
  - 1.7.x
  - master

script:
  - ./scripts/lint
  - ./scripts/build

deploy:
  - provider: script
    script: ./script/release $TRAVIS_TAG
    skip_cleanup: true
    on: 
      condition: $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
      tags: true
  - provider: script
    script: ./script/pre-release
    skip_cleanup: true
    on: 
      condition: $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
      branch: master

env:
  global:
    - secure: XAESmCJIdJ8+YxLx1rT5Yg/vWms+gzps543+pxw4GPgsdfLT155b26OhQb3uh8XLGek0V7Ii9XCL/bDzTwntoMAvuDnR0wUalPf9B6nLztzhYCBWf0c31qKWOB7UuTmL2GkCczFW4xHKFWWewrDgMiq4PPk3iBEBpK5l6yWq6PKVkGKgw0JM6QJGiPYDh/8nZWBkm9VM3gWU/iLxLrOjDwjyDRs9Li02Q0jw1HhdJRl5ybThhFmKjKyxZaJJpQvkqa+2CLOJbNFRlFypYALattTXzgQudFkoZWkRbKpQ0rCOBBHTKEhmyd8XmtoEbrylIOEfAzumKItpzQJ3XmGx3Q8u01Np2RUq9zQR5SkZdCMs9sE+8gExMnKwWuX+OwuvWLw8tQb31WgEn78RRdNUTsZ72kxsvdZ1G5cFbgn4iGUY5DhSBEBV3mKASpVEFk6SN/3diL+f8PWjBCHtemMqP5v0wP6CkB1dosQcMji4LwOizbIzYPlNOFr6mzqoqBI38PbvGetRCmjSRW4B4Wr0DTjrrgy0DIQDZXz6W1nvhcW3GhvutRp7BVgFyfWVzvNW2IDoBtJRsKLQ1GBST1D5uDg3O54gnfOs25GTkuM5KR9IGQUe3r6Z/PJSQBlEGV+eae65vCy99qqjYq+jakChs4/1LLHfKSaisrV7dxfYB8E=
