#!/bin/bash

set -ex
set -o pipefail

go get -u github.com/mitchellh/gox

gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" -osarch "linux/amd64 linux/386 darwin/amd64 darwin/386"

cd dist && shasum -a 256 * > sha256sums
