#!/bin/bash

set -ex
set -o pipefail

if test -n $GITHUB_TOKEN; then
    echo >&2 "error: please pass a \$GITHUB_TOKEN"
    exit 1
fi
if test $# -eq 0; then
    echo >&2 "error: please pass the tag to release as argument"
    exit 1
fi
TAG=$1

go get github.com/tcnksm/ghr

ghr --username seiffert --token $GITHUB_TOKEN --replace --debug $TAG dist/